# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y linux-headers-`uname -r`
    sudo apt-get install -y dkms
  displayName: 'setup'
- script: |
    sudo ./install.sh --verbose
  displayName: 'install'
